theme: picklecore
name: Privacy by RDIL
title: Privacy by RDIL
tagline: A site for all my thoughts, complaints, and worries on privacy in our technology-dependent world.
description: A site for all my thoughts, complaints, and worries on privacy in our technology-dependent world.
url: https://privacy.rdil.rocks
twitter:
  username: rdil_pickle
github: RDIL
email: me@rdil.rocks
devto: rdil
pgp: https://rdil.rocks/pgp.txt
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-archives
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-admin
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitpod.Dockerfile
  - .gitpod.yml
browserconfigxml: /browserconfig.xml
webmanifest: /manifest.json
permalink: /pages/:title:output_ext
smartify: false
jekyll-archives:
  enabled: 'all'
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
lang: en_US
license_page: /LICENSE/
