theme: picklecore
name: Privacy by RDIL
description: A site for all my thoughts, complaints, and worries on privacy in our technology-dependent world.
index_on_google: true
url: https://privacy.rdil.rocks
twitter_username: rdil_pickle
plugins:
  - jekyll-sitemap
