theme: picklecore
name: Privacy by RDIL
title: Privacy by RDIL
description: A site for all my thoughts, complaints, and worries on privacy in our technology-dependent world.
index_on_google: true
url: https://privacy.rdil.rocks
twitter:
  username: rdil_pickle
github: RDIL
email: me@rdil.rocks
devto: rdil
pgp: https://rdil.rocks/pgp.txt
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-archives
  - jekyll-relative-links
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitpod.Dockerfile
  - .gitpod.yml
keywords: "privacy,rdil,blog,thoughts,writing"
webmanifest: /manifest.json
permalink: /:title:output_ext
jekyll-archives:
  enabled: 'all'
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
